# escape=`

# Update the container tag below with one that is supported by your Windows installation
FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS build
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

RUN iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex;

# Install latest version of Sonarr
RUN choco install sonarr -y

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8 AS final

COPY --from=build C:\ProgramData\Sonarr C:\app

EXPOSE 8989
 
VOLUME [ "C:/config" ]
VOLUME [ "C:/usenet"]
WORKDIR C:\app\bin

#Launch Sonarr
CMD [ "Sonarr.Console.exe", "/data=C:\\config\\" ]